[package]
name = "eye_track_test_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.2"
opencv = "0.82.0"
rand = "0.8.5"
thiserror = "1.0.40"

eye3d = { path = "../../etvr-pye3d" }
